name: ${pluginName}
description: ${project.description}
website: ${project.url}

author: ${pluginAuthor}
version: ${project.version}

main: ${package}.${mainClass}

commands:
   ${commandName}:
      default: true
      description: ${commandDescription}
      aliases: [${commandAliases}]